/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Button: typeof import('primevue/button')['default']
    Dialog: typeof import('primevue/dialog')['default']
    PrimeVueStylingExplanation: typeof import('./src/components/PrimeVueStylingExplanation.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TabMenu: typeof import('primevue/tabmenu')['default']
  }
}
